- name: Register base install command as fact in variable install_command
  set_fact:
    install_command: "./config.sh --unattended --acceptteeeula --url {{vsts_server_url}} --auth PAT --token {{vsts_accesstoken}} --agent {{vsts_agent_name}} --work {{vsts_workfolder}} --runasservice --replace"

- name: Add agent pool to install command (default queue-agent)
  set_fact:
    install_command: "{{ install_command }} --pool {{ vsts_poolname }}"
  when: vsts_poolname|default("") != "" 

- name: Add proxy-url to install command
  set_fact:
    install_command: "{{ install_command }} --proxyurl {{ vsts_proxyurl }}"
  when: vsts_proxyurl|default("") != ""

- name: Add deployment group info to install command (deployment group agent)
  set_fact:
    install_command: "{{ install_command }} --projectname '{{ vsts_projectname }}' --deploymentgroup --deploymentgroupname {{ vsts_deploymentgroupname }} "
  register: deployment_group_set
  when: 
    - vsts_deploymentgroupname|default("") != ""
    - vsts_projectname|default("") != ""

- name: Add deployment group tags to install command (deployment group agent)
  set_fact:
    install_command: "{{ install_command }} --addDeploymentGroupTags --deploymentGroupTags {{ vsts_deploymentgrouptags|quote }} "
  when:
    - deployment_group_set is succeeded
    - vsts_deploymentgrouptags|default("") != ""

- name: Add environment info to install command
  set_fact:
    install_command: "{{ install_command }} --projectname '{{ vsts_projectname }}' --environment --environmentname {{ vsts_environmentname }} "
  register: environment_set
  when: 
    - vsts_environmentname|default("") != ""
    - vsts_projectname|default("") != ""

- name: Add virtual machine resource tags to install command
  set_fact:
    install_command: "{{ install_command }} --addvirtualmachineresourcetags --virtualmachineresourcetags {{ vsts_virtualmachineresourcetags|quote }} "
  when:
    - environment_set is succeeded
    - vsts_virtualmachineresourcetags | string

- name: Fail for conflicting options for default agent x deployment agent x environment resource
  fail:
    msg: "More than one agent type was found. Choose one of them to install. Options: vsts_poolname({{ vsts_poolname }}), vsts_deploymentgroupname({{ vsts_deploymentgroupname }}), vsts_environmentname({{ vsts_environmentname }})"
  when:
    - vsts_poolname|default("") != ""
    - vsts_deploymentgroupname|default("") != ""
    - vsts_environmentname|default("") == ""

- name: Fail for missing parameters in install command
  fail:
    msg: "Neither the vsts_poolname({{ AGENT_POOL }}) or the vsts_deploymentgroupname({{ vsts_deploymentgroupname }})  or vsts_environmentname({{ vsts_environmentname }}) vars are present, choose one of them to install."
  when:
    - vsts_poolname|default("") == ""
    - vsts_deploymentgroupname|default("") == ""
    - vsts_environmentname|default("") == ""

- name: Configure vsts-agent
  command: "{{ install_command }}"
  args:
    chdir: "{{vsts_agentfolder}}"
    creates: "{{vsts_agentfolder}}/.agent"
  become_user: "{{vsts_agent_user}}"