---
- name: Include uninstall agent tasks
  include_tasks: uninstall.yml
  when:
    -  vsts_action == 'uninstall' or vsts_action == 'reinstall'

- name: Include install agent tasks
  include_tasks: install.yml
  when: 
    - vsts_action == 'install' or vsts_action == 'reinstall'